/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface GcdsMap {
        "_controlslist"?: string;
        /**
          * @default false
         */
        "controls": boolean;
        /**
          * @default 0
         */
        "lat"?: number;
        "locale"?: any;
        /**
          * @default 0
         */
        "lon"?: number;
        /**
          * @default 'OSMTILE'
         */
        "projection"?: string;
        /**
          * @default false
         */
        "static"?: boolean;
        /**
          * Promise-based method to wait until all layers are ready Returns a promise that resolves when all child layers are fully initialized
         */
        "whenLayersReady": () => Promise<PromiseSettledResult<void>[]>;
        "whenProjectionDefined": (projection: string) => Promise<unknown>;
        /**
          * Promise-based method to wait until map is ready Returns a promise that resolves when the map is fully initialized
         */
        "whenReady": () => Promise<void>;
        /**
          * @default 0
         */
        "zoom"?: number;
    }
    interface MapA {
        "href"?: string;
        "inplace"?: boolean;
        "target"?: string;
        "type"?: string;
    }
    interface MapCaption {
    }
    interface MapExtent {
        "_label"?: string;
        "_opacity"?: number;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "hidden": boolean;
        /**
          * @default 1
         */
        "opacity"?: number;
        "units": string;
        "whenLinksReady": () => Promise<PromiseSettledResult<any>[]>;
        "whenReady": () => Promise<void>;
    }
    interface MapFeature {
        "max"?: number;
        "min"?: number;
        "whenReady": () => Promise<void>;
        "zoom"?: number;
    }
    interface MapFeaturecaption {
    }
    interface MapGeometry {
        "cs"?: string;
    }
    interface MapInput {
        "axis"?: string;
        "max"?: string;
        "min"?: string;
        "name": string;
        "position"?: string;
        "rel"?: string;
        "step"?: string;
        "type": string;
        "units"?: string;
        "value"?: string;
        "whenReady": () => Promise<void>;
    }
    interface MapLayer {
        "_opacity"?: number;
        "checked"?: boolean;
        /**
          * @default false
         */
        "hidden": boolean;
        "media"?: string;
        /**
          * @default 1
         */
        "opacity"?: number;
        "src"?: string;
        /**
          * Wait for all map-extent and map-feature elements to be ready. Returns a promise that resolves when all are settled.
         */
        "whenElemsReady": () => Promise<PromiseSettledResult<unknown>[]>;
        "whenReady": () => Promise<void>;
    }
    interface MapLink {
        "disabled"?: boolean;
        "href"?: string;
        "hreflang"?: string;
        "media"?: string;
        "projection"?: string;
        "rel"?: string;
        "tms"?: boolean;
        "tref"?: string;
        "type"?: string;
        "whenReady": () => Promise<void>;
    }
    interface MapMeta {
        "content"?: string;
        "name"?: string;
    }
    interface MapProperties {
    }
    interface MapSelect {
        "name"?: string;
        "whenReady": () => Promise<void>;
    }
    interface MapSpan {
    }
    interface MapStyle {
        "media"?: string;
    }
    interface MapTile {
        "col"?: number;
        "row"?: number;
        "src"?: string;
        "zoom"?: number;
        "zoomTo": () => Promise<void>;
    }
}
declare global {
    interface HTMLGcdsMapElement extends Components.GcdsMap, HTMLStencilElement {
    }
    var HTMLGcdsMapElement: {
        prototype: HTMLGcdsMapElement;
        new (): HTMLGcdsMapElement;
    };
    interface HTMLMapAElement extends Components.MapA, HTMLStencilElement {
    }
    var HTMLMapAElement: {
        prototype: HTMLMapAElement;
        new (): HTMLMapAElement;
    };
    interface HTMLMapCaptionElement extends Components.MapCaption, HTMLStencilElement {
    }
    var HTMLMapCaptionElement: {
        prototype: HTMLMapCaptionElement;
        new (): HTMLMapCaptionElement;
    };
    interface HTMLMapExtentElement extends Components.MapExtent, HTMLStencilElement {
    }
    var HTMLMapExtentElement: {
        prototype: HTMLMapExtentElement;
        new (): HTMLMapExtentElement;
    };
    interface HTMLMapFeatureElement extends Components.MapFeature, HTMLStencilElement {
    }
    var HTMLMapFeatureElement: {
        prototype: HTMLMapFeatureElement;
        new (): HTMLMapFeatureElement;
    };
    interface HTMLMapFeaturecaptionElement extends Components.MapFeaturecaption, HTMLStencilElement {
    }
    var HTMLMapFeaturecaptionElement: {
        prototype: HTMLMapFeaturecaptionElement;
        new (): HTMLMapFeaturecaptionElement;
    };
    interface HTMLMapGeometryElement extends Components.MapGeometry, HTMLStencilElement {
    }
    var HTMLMapGeometryElement: {
        prototype: HTMLMapGeometryElement;
        new (): HTMLMapGeometryElement;
    };
    interface HTMLMapInputElement extends Components.MapInput, HTMLStencilElement {
    }
    var HTMLMapInputElement: {
        prototype: HTMLMapInputElement;
        new (): HTMLMapInputElement;
    };
    interface HTMLMapLayerElement extends Components.MapLayer, HTMLStencilElement {
    }
    var HTMLMapLayerElement: {
        prototype: HTMLMapLayerElement;
        new (): HTMLMapLayerElement;
    };
    interface HTMLMapLinkElement extends Components.MapLink, HTMLStencilElement {
    }
    var HTMLMapLinkElement: {
        prototype: HTMLMapLinkElement;
        new (): HTMLMapLinkElement;
    };
    interface HTMLMapMetaElement extends Components.MapMeta, HTMLStencilElement {
    }
    var HTMLMapMetaElement: {
        prototype: HTMLMapMetaElement;
        new (): HTMLMapMetaElement;
    };
    interface HTMLMapPropertiesElement extends Components.MapProperties, HTMLStencilElement {
    }
    var HTMLMapPropertiesElement: {
        prototype: HTMLMapPropertiesElement;
        new (): HTMLMapPropertiesElement;
    };
    interface HTMLMapSelectElement extends Components.MapSelect, HTMLStencilElement {
    }
    var HTMLMapSelectElement: {
        prototype: HTMLMapSelectElement;
        new (): HTMLMapSelectElement;
    };
    interface HTMLMapSpanElement extends Components.MapSpan, HTMLStencilElement {
    }
    var HTMLMapSpanElement: {
        prototype: HTMLMapSpanElement;
        new (): HTMLMapSpanElement;
    };
    interface HTMLMapStyleElement extends Components.MapStyle, HTMLStencilElement {
    }
    var HTMLMapStyleElement: {
        prototype: HTMLMapStyleElement;
        new (): HTMLMapStyleElement;
    };
    interface HTMLMapTileElement extends Components.MapTile, HTMLStencilElement {
    }
    var HTMLMapTileElement: {
        prototype: HTMLMapTileElement;
        new (): HTMLMapTileElement;
    };
    interface HTMLElementTagNameMap {
        "gcds-map": HTMLGcdsMapElement;
        "map-a": HTMLMapAElement;
        "map-caption": HTMLMapCaptionElement;
        "map-extent": HTMLMapExtentElement;
        "map-feature": HTMLMapFeatureElement;
        "map-featurecaption": HTMLMapFeaturecaptionElement;
        "map-geometry": HTMLMapGeometryElement;
        "map-input": HTMLMapInputElement;
        "map-layer": HTMLMapLayerElement;
        "map-link": HTMLMapLinkElement;
        "map-meta": HTMLMapMetaElement;
        "map-properties": HTMLMapPropertiesElement;
        "map-select": HTMLMapSelectElement;
        "map-span": HTMLMapSpanElement;
        "map-style": HTMLMapStyleElement;
        "map-tile": HTMLMapTileElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface GcdsMap {
        "_controlslist"?: string;
        /**
          * @default false
         */
        "controls"?: boolean;
        /**
          * @default 0
         */
        "lat"?: number;
        "locale"?: any;
        /**
          * @default 0
         */
        "lon"?: number;
        /**
          * @default 'OSMTILE'
         */
        "projection"?: string;
        /**
          * @default false
         */
        "static"?: boolean;
        /**
          * @default 0
         */
        "zoom"?: number;
    }
    interface MapA {
        "href"?: string;
        "inplace"?: boolean;
        "target"?: string;
        "type"?: string;
    }
    interface MapCaption {
    }
    interface MapExtent {
        "_label"?: string;
        "_opacity"?: number;
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default false
         */
        "hidden"?: boolean;
        /**
          * @default 1
         */
        "opacity"?: number;
        "units": string;
    }
    interface MapFeature {
        "max"?: number;
        "min"?: number;
        "zoom"?: number;
    }
    interface MapFeaturecaption {
    }
    interface MapGeometry {
        "cs"?: string;
    }
    interface MapInput {
        "axis"?: string;
        "max"?: string;
        "min"?: string;
        "name": string;
        "position"?: string;
        "rel"?: string;
        "step"?: string;
        "type": string;
        "units"?: string;
        "value"?: string;
    }
    interface MapLayer {
        "_opacity"?: number;
        "checked"?: boolean;
        /**
          * @default false
         */
        "hidden"?: boolean;
        "media"?: string;
        /**
          * @default 1
         */
        "opacity"?: number;
        "src"?: string;
    }
    interface MapLink {
        "disabled"?: boolean;
        "href"?: string;
        "hreflang"?: string;
        "media"?: string;
        "projection"?: string;
        "rel"?: string;
        "tms"?: boolean;
        "tref"?: string;
        "type"?: string;
    }
    interface MapMeta {
        "content"?: string;
        "name"?: string;
    }
    interface MapProperties {
    }
    interface MapSelect {
        "name"?: string;
    }
    interface MapSpan {
    }
    interface MapStyle {
        "media"?: string;
    }
    interface MapTile {
        "col"?: number;
        "row"?: number;
        "src"?: string;
        "zoom"?: number;
    }

    interface GcdsMapAttributes {
        "lat": number;
        "lon": number;
        "zoom": number;
        "projection": string;
        "controls": boolean;
        "static": boolean;
        "_controlslist": string;
        "locale": string;
    }
    interface MapAAttributes {
        "href": string;
        "target": string;
        "type": string;
        "inplace": boolean;
    }
    interface MapExtentAttributes {
        "checked": boolean;
        "_label": string;
        "opacity": number;
        "_opacity": number;
        "hidden": boolean;
        "units": string;
        "disabled": boolean;
    }
    interface MapFeatureAttributes {
        "zoom": number;
        "min": number;
        "max": number;
    }
    interface MapGeometryAttributes {
        "cs": string;
    }
    interface MapInputAttributes {
        "name": string;
        "type": string;
        "value": string;
        "axis": string;
        "units": string;
        "position": string;
        "rel": string;
        "min": string;
        "max": string;
        "step": string;
    }
    interface MapLayerAttributes {
        "src": string;
        "checked": boolean;
        "hidden": boolean;
        "opacity": number;
        "_opacity": number;
        "media": string;
    }
    interface MapLinkAttributes {
        "type": string;
        "rel": string;
        "href": string;
        "hreflang": string;
        "tref": string;
        "media": string;
        "tms": boolean;
        "projection": string;
        "disabled": boolean;
    }
    interface MapMetaAttributes {
        "name": string;
        "content": string;
    }
    interface MapSelectAttributes {
        "name": string;
    }
    interface MapStyleAttributes {
        "media": string;
    }
    interface MapTileAttributes {
        "row": number;
        "col": number;
        "zoom": number;
        "src": string;
    }

    interface IntrinsicElements {
        "gcds-map": Omit<GcdsMap, keyof GcdsMapAttributes> & { [K in keyof GcdsMap & keyof GcdsMapAttributes]?: GcdsMap[K] } & { [K in keyof GcdsMap & keyof GcdsMapAttributes as `attr:${K}`]?: GcdsMapAttributes[K] } & { [K in keyof GcdsMap & keyof GcdsMapAttributes as `prop:${K}`]?: GcdsMap[K] };
        "map-a": Omit<MapA, keyof MapAAttributes> & { [K in keyof MapA & keyof MapAAttributes]?: MapA[K] } & { [K in keyof MapA & keyof MapAAttributes as `attr:${K}`]?: MapAAttributes[K] } & { [K in keyof MapA & keyof MapAAttributes as `prop:${K}`]?: MapA[K] };
        "map-caption": MapCaption;
        "map-extent": Omit<MapExtent, keyof MapExtentAttributes> & { [K in keyof MapExtent & keyof MapExtentAttributes]?: MapExtent[K] } & { [K in keyof MapExtent & keyof MapExtentAttributes as `attr:${K}`]?: MapExtentAttributes[K] } & { [K in keyof MapExtent & keyof MapExtentAttributes as `prop:${K}`]?: MapExtent[K] } & OneOf<"units", MapExtent["units"], MapExtentAttributes["units"]>;
        "map-feature": Omit<MapFeature, keyof MapFeatureAttributes> & { [K in keyof MapFeature & keyof MapFeatureAttributes]?: MapFeature[K] } & { [K in keyof MapFeature & keyof MapFeatureAttributes as `attr:${K}`]?: MapFeatureAttributes[K] } & { [K in keyof MapFeature & keyof MapFeatureAttributes as `prop:${K}`]?: MapFeature[K] };
        "map-featurecaption": MapFeaturecaption;
        "map-geometry": Omit<MapGeometry, keyof MapGeometryAttributes> & { [K in keyof MapGeometry & keyof MapGeometryAttributes]?: MapGeometry[K] } & { [K in keyof MapGeometry & keyof MapGeometryAttributes as `attr:${K}`]?: MapGeometryAttributes[K] } & { [K in keyof MapGeometry & keyof MapGeometryAttributes as `prop:${K}`]?: MapGeometry[K] };
        "map-input": Omit<MapInput, keyof MapInputAttributes> & { [K in keyof MapInput & keyof MapInputAttributes]?: MapInput[K] } & { [K in keyof MapInput & keyof MapInputAttributes as `attr:${K}`]?: MapInputAttributes[K] } & { [K in keyof MapInput & keyof MapInputAttributes as `prop:${K}`]?: MapInput[K] } & OneOf<"name", MapInput["name"], MapInputAttributes["name"]> & OneOf<"type", MapInput["type"], MapInputAttributes["type"]>;
        "map-layer": Omit<MapLayer, keyof MapLayerAttributes> & { [K in keyof MapLayer & keyof MapLayerAttributes]?: MapLayer[K] } & { [K in keyof MapLayer & keyof MapLayerAttributes as `attr:${K}`]?: MapLayerAttributes[K] } & { [K in keyof MapLayer & keyof MapLayerAttributes as `prop:${K}`]?: MapLayer[K] };
        "map-link": Omit<MapLink, keyof MapLinkAttributes> & { [K in keyof MapLink & keyof MapLinkAttributes]?: MapLink[K] } & { [K in keyof MapLink & keyof MapLinkAttributes as `attr:${K}`]?: MapLinkAttributes[K] } & { [K in keyof MapLink & keyof MapLinkAttributes as `prop:${K}`]?: MapLink[K] };
        "map-meta": Omit<MapMeta, keyof MapMetaAttributes> & { [K in keyof MapMeta & keyof MapMetaAttributes]?: MapMeta[K] } & { [K in keyof MapMeta & keyof MapMetaAttributes as `attr:${K}`]?: MapMetaAttributes[K] } & { [K in keyof MapMeta & keyof MapMetaAttributes as `prop:${K}`]?: MapMeta[K] };
        "map-properties": MapProperties;
        "map-select": Omit<MapSelect, keyof MapSelectAttributes> & { [K in keyof MapSelect & keyof MapSelectAttributes]?: MapSelect[K] } & { [K in keyof MapSelect & keyof MapSelectAttributes as `attr:${K}`]?: MapSelectAttributes[K] } & { [K in keyof MapSelect & keyof MapSelectAttributes as `prop:${K}`]?: MapSelect[K] };
        "map-span": MapSpan;
        "map-style": Omit<MapStyle, keyof MapStyleAttributes> & { [K in keyof MapStyle & keyof MapStyleAttributes]?: MapStyle[K] } & { [K in keyof MapStyle & keyof MapStyleAttributes as `attr:${K}`]?: MapStyleAttributes[K] } & { [K in keyof MapStyle & keyof MapStyleAttributes as `prop:${K}`]?: MapStyle[K] };
        "map-tile": Omit<MapTile, keyof MapTileAttributes> & { [K in keyof MapTile & keyof MapTileAttributes]?: MapTile[K] } & { [K in keyof MapTile & keyof MapTileAttributes as `attr:${K}`]?: MapTileAttributes[K] } & { [K in keyof MapTile & keyof MapTileAttributes as `prop:${K}`]?: MapTile[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "gcds-map": LocalJSX.IntrinsicElements["gcds-map"] & JSXBase.HTMLAttributes<HTMLGcdsMapElement>;
            "map-a": LocalJSX.IntrinsicElements["map-a"] & JSXBase.HTMLAttributes<HTMLMapAElement>;
            "map-caption": LocalJSX.IntrinsicElements["map-caption"] & JSXBase.HTMLAttributes<HTMLMapCaptionElement>;
            "map-extent": LocalJSX.IntrinsicElements["map-extent"] & JSXBase.HTMLAttributes<HTMLMapExtentElement>;
            "map-feature": LocalJSX.IntrinsicElements["map-feature"] & JSXBase.HTMLAttributes<HTMLMapFeatureElement>;
            "map-featurecaption": LocalJSX.IntrinsicElements["map-featurecaption"] & JSXBase.HTMLAttributes<HTMLMapFeaturecaptionElement>;
            "map-geometry": LocalJSX.IntrinsicElements["map-geometry"] & JSXBase.HTMLAttributes<HTMLMapGeometryElement>;
            "map-input": LocalJSX.IntrinsicElements["map-input"] & JSXBase.HTMLAttributes<HTMLMapInputElement>;
            "map-layer": LocalJSX.IntrinsicElements["map-layer"] & JSXBase.HTMLAttributes<HTMLMapLayerElement>;
            "map-link": LocalJSX.IntrinsicElements["map-link"] & JSXBase.HTMLAttributes<HTMLMapLinkElement>;
            "map-meta": LocalJSX.IntrinsicElements["map-meta"] & JSXBase.HTMLAttributes<HTMLMapMetaElement>;
            "map-properties": LocalJSX.IntrinsicElements["map-properties"] & JSXBase.HTMLAttributes<HTMLMapPropertiesElement>;
            "map-select": LocalJSX.IntrinsicElements["map-select"] & JSXBase.HTMLAttributes<HTMLMapSelectElement>;
            "map-span": LocalJSX.IntrinsicElements["map-span"] & JSXBase.HTMLAttributes<HTMLMapSpanElement>;
            "map-style": LocalJSX.IntrinsicElements["map-style"] & JSXBase.HTMLAttributes<HTMLMapStyleElement>;
            "map-tile": LocalJSX.IntrinsicElements["map-tile"] & JSXBase.HTMLAttributes<HTMLMapTileElement>;
        }
    }
}
